

version: '2'
  
services:

  mongodb:
    image : mongo:latest
    container_name: mongodb_faceid
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: faceid-app
    volumes:
      - ./MongoDB_FaceApp/mongodb/database:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017
    restart: unless-stopped

  faceid:
    build: .
    container_name: faceidapp
    ports: 
      - 8501:8501
    
    links:
      - mongodb

    restart: unless-stopped



    deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: 1
                  capabilities: [gpu]
